//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int MaAD { get; set; }
        public string Ho_TenDem { get; set; }
        public string TenAD { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string Username { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string AnhDaiDien { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
