//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSP
    {
        public string TaiKhoan { get; set; }
        public int MaSP { get; set; }
        public string NoiDungDinhGia { get; set; }
        public System.DateTime ThoiGianDang { get; set; }
    
        public virtual TaiKhoan TaiKhoan1 { get; set; }
        public virtual Thuoc Thuoc { get; set; }
    }
}
