//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaGH { get; set; }
        public int MaKH { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public double ThanhTien { get; set; }
        public System.DateTime ThoiGianCapNhat { get; set; }
        public Nullable<int> MaHD { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Thuoc Thuoc { get; set; }
    }
}
